Ever since patchset 8648 (xen-unstable.hg) all my configuration files fail with the following:
Error: Device 768 (vbd) could not be connected. Hotplug scripts not working.

(Since my HVM tree follows xen-unstable.hg closely, it breaks too).

The following patch undoes a small part of Ke Yu's patch and fixes the
problem.

However, I'm having trouble understanding what this part did in the
original patch. Was there a subtle change in the disk variable format
that I missed?

Signed-Off-By: Leendert van Doorn <leendert@watson.ibm.com>